<?php
$malaria = array(
"vaccine preparation" => "1",
"pvs25" => "39",
"plasmodium spp. protein" => "39",
"me-trap" => "5",
"aluminium hydroxide" => "12",
"vaccine combination b" => "1",
"plasmodium gene" => "25",
"fmp1/as02a" => "4",
"protozoan gene" => "25",
"fmp1" => "4",
"as02a" => "21",
"montanide isa-720" => "5",
"msp3-lsp" => "4",
"protozoan vaccine" => "1259",
"malaria vaccine" => "1259",
"malaria vaccine fmp1/as02a" => "1",
"fmp1/as02a malaria vaccine" => "1",
"parasite protein" => "184");
?>